"use client";

import { useMemo, useState } from "react";

const stageLabel = { opportunity:"Opportunità", connection:"Connessione", go_decision:"GO / NO-GO", development:"Sviluppo", presentation:"Presentazione", authorization:"Autorizzazione", commercial:"Commerciale", authorized:"Autorizzato", closed:"Chiuso" };
const riskLabel = { normal:"Normale", attention:"Attenzione", critical:"Critico" };

function Badge({ children, tone="neutral" }) { return <span className={`pl-badge pl-${tone}`}>{children}</span>; }

export default function ViscontiProjectListV2({ projects = [], connected = false }) {
  const [query, setQuery] = useState("");
  const [stage, setStage] = useState("all");
  const rows = useMemo(() => projects.filter(p => {
    const text = `${p.name||""} ${p.region||""}`.toLowerCase();
    return (!query || text.includes(query.toLowerCase())) && (stage === "all" || p.project_stage === stage);
  }), [projects, query, stage]);

  return <main className="pl-shell"><style>{`.pl-shell{min-height:100vh;background:#f6f7f9;color:#172033;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.pl-top{background:#fff;border-bottom:1px solid #e6e9ef;padding:15px 34px;display:flex;justify-content:space-between;align-items:center}.pl-brand{font-weight:800;font-size:14px}.pl-back{display:block;color:#697386;text-decoration:none;font-size:11px;margin-bottom:4px}.pl-main{max-width:1320px;margin:auto;padding:30px 34px 50px}.pl-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.pl-kicker{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#8a92a1;font-weight:800}.pl-title{font-size:30px;letter-spacing:-.04em;margin:5px 0}.pl-sub{font-size:13px;color:#737c8c}.pl-actions{display:flex;gap:8px}.pl-btn{border:1px solid #dfe3e9;background:#fff;border-radius:9px;padding:9px 13px;font-size:11px;font-weight:750;text-decoration:none;color:#172033}.pl-primary{background:#172b4d;color:#fff;border-color:#172b4d}.pl-tools{margin:22px 0 12px;display:flex;gap:8px;flex-wrap:wrap}.pl-input,.pl-select{border:1px solid #dfe3e9;border-radius:9px;background:#fff;padding:9px 11px;font:inherit;font-size:11px}.pl-input{min-width:260px}.pl-card{background:#fff;border:1px solid #e6e9ef;border-radius:14px;overflow:hidden;box-shadow:0 2px 10px rgba(20,28,45,.03)}.pl-row{display:grid;grid-template-columns:1.7fr .8fr .6fr .9fr .75fr .8fr;gap:12px;padding:14px 16px;border-top:1px solid #edf0f3;align-items:center}.pl-row:first-child{border-top:0}.pl-row-head{background:#fafbfc;color:#9299a6;text-transform:uppercase;letter-spacing:.06em;font-size:9px;font-weight:800}.pl-row:not(.pl-row-head){font-size:11px}.pl-name{font-weight:800;font-size:12px}.pl-muted{color:#7c8493;font-size:10px;margin-top:3px}.pl-badge{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:800;white-space:nowrap}.pl-normal{background:#edf3ff;color:#3d61ad}.pl-attention{background:#fff5df;color:#996400}.pl-critical{background:#fff0ef;color:#b43a34}.pl-neutral{background:#f0f2f5;color:#626b7a}.pl-empty{padding:35px;text-align:center;color:#7c8493;font-size:12px}.pl-note{margin-top:12px;color:#8a92a1;font-size:10px}@media(max-width:900px){.pl-main{padding:22px 18px}.pl-top{padding:14px 18px}.pl-row{grid-template-columns:1.5fr 1fr .7fr;}.pl-row-head{display:none}.pl-row>div:nth-child(n+4){display:none}.pl-input{min-width:180px}}`}</style>
    <header className="pl-top"><div><a className="pl-back" href="/visconti-work">← Control Tower</a><div className="pl-brand">GRUPPO VISCONTI · WORK V2</div></div><div className="pl-actions"><a className="pl-btn" href="/visconti-work/connection">Connessioni</a></div></header>
    <section className="pl-main"><div className="pl-head"><div><div className="pl-kicker">Portafoglio operativo</div><h1 className="pl-title">Progetti</h1><p className="pl-sub">Una vista unica di fase, rischio, attività e prossima azione.</p></div><a className="pl-btn pl-primary" href="/visconti-work">Control Tower</a></div>
      <div className="pl-tools"><input className="pl-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca progetto o regione…"/><select className="pl-select" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">Tutte le fasi</option>{Object.entries(stageLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
      <div className="pl-card"><div className="pl-row pl-row-head"><div>Progetto</div><div>Fase</div><div>MW</div><div>Rischio</div><div>Attività</div><div>Prossima azione</div></div>{rows.map(p=><a key={p.id} href={`/visconti-work/projects?id=${encodeURIComponent(p.id)}`} className="pl-row" style={{textDecoration:"none",color:"inherit"}}><div><div className="pl-name">{p.name}</div><div className="pl-muted">{p.region||"Regione non indicata"}</div></div><div><Badge tone="neutral">{stageLabel[p.project_stage]||p.project_stage||"—"}</Badge></div><div>{p.mw||0}</div><div><Badge tone={p.risk_level||"normal"}>{riskLabel[p.risk_level]||p.risk_level||"Normale"}</Badge></div><div>{p.open_tasks||0} aperte{p.blocked_tasks?` · ${p.blocked_tasks} bloccate`:""}</div><div className="pl-muted">{p.next_action||"Nessuna azione registrata"}</div></a>)}{!rows.length&&<div className="pl-empty">{connected?"Nessun progetto corrisponde ai filtri.":"Nessun dato Supabase disponibile. Configura il collegamento per vedere i progetti reali."}</div>}</div>
      <div className="pl-note">{connected ? `${rows.length} progetti visualizzati.` : "Modalità dimostrativa: la struttura dell’app è pronta, ma i dati reali richiedono Supabase configurato."}</div>
    </section></main>;
}
