"use client";
import { useEffect, useMemo, useState } from "react";

async function projectRequest(projectId, fields) {
  const r = await fetch("/api/visconti-project-spv", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, fields }), cache: "no-store" });
  const t = await r.text(); let d = {};
  try { d = t ? JSON.parse(t) : {}; } catch (_) {}
  if (!r.ok) throw new Error(d.error || `Operazione non riuscita (${r.status}).`);
  return d;
}

const transferLabels = { not_started: "Non avviata", to_request: "Da richiedere", in_progress: "In corso", integrations: "Integrazioni", accepted: "Accettata", completed: "Completata", not_applicable: "Non applicabile" };
const spvItems = [
  ["Costituzione SPV", "spv_incorporation_done", "spv_incorporation_received", "spv_incorporation_done_at", "spv_incorporation_received_at"],
  ["P.IVA", "spv_vat_done", "spv_vat_received", "spv_vat_done_at", "spv_vat_received_at"],
  ["PEC", "spv_pec_done", "spv_pec_received", "spv_pec_done_at", "spv_pec_received_at"],
];

function Tracking({ item, project, save }) {
  const [label, doneField, receivedField, doneAt, receivedAt] = item;
  const done = !!project[doneAt]; const received = !!project[receivedAt];
  return <div className="spv-track"><div><b>{label}</b><small>{done ? `Fatto ${new Date(doneAt).toLocaleDateString("it-IT")}` : "Non fatto"}{received ? ` · Ricevuto ${new Date(receivedAt).toLocaleDateString("it-IT")}` : " · Ricevuto non registrato"}</small></div><button className={`spv-btn ${done ? "spv-ok" : ""}`} onClick={() => save({ [doneField]: !done })}>{done ? "FATTO ✓" : "Segna FATTO"}</button><button className={`spv-btn ${received ? "spv-ok" : ""}`} disabled={!done} onClick={() => save({ [receivedField]: !received })}>{received ? "RICEVUTO ✓" : "Segna RICEVUTO"}</button></div>;
}

export default function ViscontiProjectSpvWorkflow({ projectId }) {
  const [project, setProject] = useState(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!projectId) return; fetch(`/api/visconti-project-spv?projectId=${encodeURIComponent(projectId)}`, { cache: "no-store" }).then(async r => { const t = await r.text(); let d = {}; try { d = t ? JSON.parse(t) : {}; } catch (_) {} if (!r.ok) throw new Error(d.error || "Lettura progetto non riuscita."); return d; }).then(setProject).catch(e => setError(e.message)); }, [projectId]);
  const requiresSpv = project?.requires_spv !== false; const go = project?.go_no_go_status || "pending"; const spvReady = project?.spv_status === "created"; const transferReady = project?.connection_transfer_status === "completed";
  const nextStep = useMemo(() => { if (go === "pending") return "Decidere GO / NO-GO"; if (go === "no_go") return "Archiviare il progetto"; if (!requiresSpv) return "Gestione diretta: nessuna SPV, P.IVA/PEC societaria o voltura"; if (!spvReady) return "Costituire la società veicolo"; if (!transferReady) return "Richiedere e completare la voltura della connessione"; return "Voltura completata"; }, [go, requiresSpv, spvReady, transferReady]);
  async function save(fields) { if (!project || saving) return; setSaving(true); setError(""); try { await projectRequest(project.id, fields); const fresh = await fetch(`/api/visconti-project-spv?projectId=${encodeURIComponent(project.id)}`, { cache: "no-store" }).then(r => r.json()); setProject(fresh); } catch (e) { setError(e.message || "Salvataggio non riuscito."); } finally { setSaving(false); } }
  async function decide(decision) { if (!project || !window.confirm(decision === "go" ? "Confermare GO per questo progetto?" : "Confermare NO-GO? Il progetto potrà essere archiviato.")) return; setSaving(true); setError(""); try { const r = await fetch("/api/visconti-control-tower-decision", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId: project.id, decision }) }); const t = await r.text(); let d = {}; try { d = t ? JSON.parse(t) : {}; } catch (_) {} if (!r.ok) throw new Error(d.error || `Operazione non riuscita (${r.status})`); setProject(p => ({ ...p, ...d, go_no_go_status: decision })); } catch (e) { setError(e.message || "Operazione non riuscita."); } finally { setSaving(false); } }
  if (!project) return null;
  return <section className="spv-card"><style>{`.spv-card{margin-top:18px;background:#fff;border:1px solid #e7e9ee;border-radius:14px;padding:20px;box-shadow:0 2px 10px rgba(20,28,45,.03);font-family:Inter,ui-sans-serif,system-ui;color:#172033}.spv-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.spv-kicker{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#8a92a1;font-weight:800}.spv-title{font-size:17px;font-weight:800;margin-top:5px}.spv-next{font-size:11px;color:#687181;margin-top:5px}.spv-actions{display:flex;gap:7px;flex-wrap:wrap}.spv-btn{border:1px solid #dfe3e9;background:#fff;border-radius:9px;padding:8px 11px;font-size:10px;font-weight:800;cursor:pointer}.spv-btn:disabled{opacity:.45;cursor:not-allowed}.spv-ok{background:#eaf8f1;border-color:#b8e2cc;color:#18794e}.spv-go{background:#172b4d;color:#fff;border-color:#172b4d}.spv-no{color:#a33;background:#fff6f5}.spv-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}.spv-box{background:#f8f9fb;border-radius:10px;padding:12px}.spv-box small{display:block;color:#8a92a1;font-size:9px;text-transform:uppercase}.spv-box b{display:block;margin-top:5px;font-size:12px}.spv-direct{margin-top:16px;padding:14px;border-radius:11px;background:#f5f8fc;border:1px solid #dce5f1}.spv-direct b{font-size:12px}.spv-direct p{margin:5px 0 0;font-size:10px;color:#687181}.spv-section{margin-top:17px;padding-top:15px;border-top:1px solid #eef0f3}.spv-section h4{margin:0 0 9px;font-size:12px}.spv-form{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.spv-form input{width:100%;box-sizing:border-box;border:1px solid #dfe3e9;border-radius:8px;padding:8px;font-size:11px}.spv-track{display:grid;grid-template-columns:1.5fr 1fr 1fr;gap:8px;align-items:center;margin-top:10px}.spv-track b{font-size:11px;display:block}.spv-track small{font-size:9px;color:#7a8392;display:block;margin-top:3px}.spv-error{color:#b43a34;font-size:10px;margin-top:9px}@media(max-width:800px){.spv-grid,.spv-form{grid-template-columns:1fr 1fr}}@media(max-width:560px){.spv-head{display:block}.spv-actions{margin-top:12px}.spv-grid,.spv-form,.spv-track{grid-template-columns:1fr}}`}</style>
    <div className="spv-head"><div><div className="spv-kicker">Percorso societario</div><div className="spv-title">{requiresSpv ? "GO / NO-GO → SPV → voltura" : "GO / NO-GO → presentazione diretta"}</div><div className="spv-next"><b>Prossimo passo:</b> {nextStep}</div></div><div className="spv-actions"><button className="spv-btn spv-go" disabled={saving || go === "go"} onClick={() => decide("go")}>{go === "go" ? "GO confermato" : "Conferma GO"}</button><button className="spv-btn spv-no" disabled={saving || go === "no_go"} onClick={() => decide("no_go")}>{go === "no_go" ? "NO-GO confermato" : "Conferma NO-GO"}</button></div></div>
    <div className="spv-grid"><div className="spv-box"><small>Decisione</small><b>{go === "go" ? "GO" : go === "no_go" ? "NO-GO" : "Da decidere"}</b></div><div className="spv-box"><small>Titolare / presentatore</small><b>{project.proposer_company || project.connection_holder || "Gruppo Visconti Srl"}</b></div><div className="spv-box"><small>{requiresSpv ? "Voltura connessione" : "Gestione societaria"}</small><b>{requiresSpv ? (transferLabels[project.connection_transfer_status] || project.connection_transfer_status) : "Nessuna SPV · nessuna voltura"}</b></div></div>
    {!requiresSpv && <div className="spv-direct"><b>Progetto gestito direttamente da Gruppo Visconti S.r.l.</b><p>Progettazione: {project.developer_company || "Gruppo Visconti Servizi"}. Il progetto non genera attività per costituzione SPV, apertura P.IVA/PEC o voltura.</p></div>}
    {requiresSpv && go === "go" && <><div className="spv-section"><h4>Società veicolo</h4><div className="spv-form">{[["Nome SPV","spv_name"],["P.IVA","spv_vat_number"],["Codice fiscale","spv_tax_code"],["PEC","spv_pec"],["Sede","spv_registered_office"],["Data costituzione YYYY-MM-DD","spv_incorporation_date"]].map(([placeholder,key]) => <input key={key} placeholder={placeholder} value={project[key] || ""} onChange={e => setProject(p => ({...p,[key]:e.target.value}))} onBlur={e => save({[key]:e.target.value || null})} />)}</div><div className="spv-actions" style={{marginTop:10}}><button className="spv-btn" disabled={saving} onClick={() => save({spv_status:"in_progress"})}>Costituzione in corso</button><button className="spv-btn" disabled={saving} onClick={() => save({spv_status:"created"})}>Segna SPV costituita</button></div><div className="spv-section"><h4>Controllo documentale</h4>{spvItems.map(item => <Tracking key={item[0]} item={item} project={project} save={save} />)}</div></div><div className="spv-section"><h4>Voltura della connessione</h4><div className="spv-form"><input placeholder="Protocollo voltura" value={project.connection_transfer_protocol || ""} onChange={e => setProject(p => ({...p,connection_transfer_protocol:e.target.value}))} onBlur={e => save({connection_transfer_protocol:e.target.value || null})} /><input placeholder="Data richiesta YYYY-MM-DD" value={project.connection_transfer_request_date || ""} onChange={e => setProject(p => ({...p,connection_transfer_request_date:e.target.value}))} onBlur={e => save({connection_transfer_request_date:e.target.value || null})} /><input placeholder="Data completamento YYYY-MM-DD" value={project.connection_transfer_completed_date || ""} onChange={e => setProject(p => ({...p,connection_transfer_completed_date:e.target.value}))} onBlur={e => save({connection_transfer_completed_date:e.target.value || null})} /><input placeholder="Protocollo / conferma ricevuta" value={project.connection_transfer_received_protocol || ""} onChange={e => setProject(p => ({...p,connection_transfer_received_protocol:e.target.value}))} onBlur={e => save({connection_transfer_received_protocol:e.target.value || null})} /></div><div className="spv-actions" style={{marginTop:10}}><button className="spv-btn" disabled={saving} onClick={() => save({connection_transfer_status:"in_progress"})}>Voltura richiesta / in corso</button><button className="spv-btn" disabled={saving || !spvReady} onClick={() => save({connection_transfer_status:"completed",connection_holder:project.spv_name || "SPV"})}>Segna voltura completata</button></div></div></>}
    {error && <div className="spv-error">{error}</div>}
  </section>;
}
