"use client";

import { useMemo, useState } from "react";

const AREAS=[{area:"Connessioni",people:["Dario"]},{area:"Richieste",people:["Federica"]},{area:"PTO",people:["Giggi","Dario"]}];
const TEAM=["Dario","Roberto","Carmelo","Francesco"];
const norm=v=>String(v||"").trim().toLowerCase();
const areaOf=t=>{const x=`${t.title||""} ${t.description||""} ${t.category||""}`.toLowerCase();if(/pto/.test(x))return"PTO";if(/richiest|request/.test(x))return"Richieste";if(/connession|terna|tica|preventiv|voltura/.test(x)||t.connection_practice_id)return"Connessioni";return""};
const status=t=>t.workflow_status==="done"?"Fatto":t.workflow_status==="blocked"||t.attention_state==="blocked"?"Bloccato":t.workflow_status==="in_progress"?"In corso":t.due_date&&t.due_date<new Date().toISOString().slice(0,10)?"Scaduto":"Da fare";
export default function ViscontiWeeklyResponsibilityBoardV2({tasks=[],members=[]}){const[filter,setFilter]=useState("Tutte");const visible=useMemo(()=>tasks.filter(t=>t.workflow_status!=="cancelled"&&(filter==="Tutte"||areaOf(t)===filter)),[tasks,filter]);return <section style={{maxWidth:1450,margin:"0 auto",padding:"0 34px 22px",fontFamily:"Inter,system-ui"}}><div style={{border:"1px solid #dfe4eb",background:"#fff",borderRadius:14,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-end",marginBottom:15}}><div><div style={{fontSize:9,letterSpacing:'.14em',textTransform:'uppercase',color:'#7b8696',fontWeight:850}}>Agenda operativa di Vincenzo</div><div style={{fontSize:18,fontWeight:900,marginTop:4}}>Questa settimana: cosa deve succedere</div><div style={{fontSize:10,color:'#6d7787',marginTop:5}}>Lettura delle attività reali. Nessuna riassegnazione automatica.</div></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{['Tutte',...AREAS.map(a=>a.area)].map(x=><button key={x} onClick={()=>setFilter(x)} style={{border:'1px solid #d9dee6',borderRadius:999,padding:'7px 11px',fontSize:9,fontWeight:800,background:filter===x?'#172b4d':'#fff',color:filter===x?'#fff':'#596577'}}>{x}</button>)}</div></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}>{TEAM.map(p=>{const ts=visible.filter(t=>norm(t.assignee_name)===norm(p));return <div key={p} style={{border:'1px solid #e0e5eb',borderRadius:11,padding:12,minHeight:145}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:9}}><b style={{fontSize:13}}>{p}</b><span style={{fontSize:9,color:'#748092'}}>{ts.length} attività</span></div>{ts.slice(0,6).map(t=><div key={t.id} style={{borderTop:'1px solid #edf0f3',padding:'8px 0'}}><div style={{fontSize:10,fontWeight:800}}>{t.title||'Attività senza titolo'}</div><div style={{fontSize:8,color:'#7a8594',marginTop:4,display:'flex',justifyContent:'space-between'}}><span>{t.project_name||'—'}</span><span>{status(t)}</span></div></div>)}{!ts.length&&<div style={{fontSize:9,color:'#8993a0'}}>Nessuna attività assegnata visibile.</div>}</div>})}</div><div style={{marginTop:13,paddingTop:11,borderTop:'1px solid #e9edf1',fontSize:9,color:'#737e8d'}}><b>Regola del lunedì:</b> verificare il lavoro precedente, poi chiudere, continuare, sbloccare/attendere un esterno o assegnare il nuovo incarico.</div></div></section>}
