"use client";
import Link from "next/link";

const spvLabel = { to_create: "SPV da costituire", in_progress: "SPV in costituzione", created: "SPV costituita" };
const transferLabel = { to_request: "Voltura da richiedere", in_progress: "Voltura in corso", integrations: "Voltura: integrazioni", accepted: "Voltura accettata", completed: "Voltura completata" };

export default function ViscontiPostGoPanel({ data = {} }) {
  const rows = (data.projects || []).filter((p) => p.project_status !== "archived" && p.go_no_go_status === "go");
  if (!rows.length) return null;
  const next = (p) => p.spv_status !== "created" ? "Costituire SPV + completare P.IVA/PEC" : p.connection_transfer_status !== "completed" ? "Richiedere/completare voltura" : "Nessuna azione societaria aperta";
  return <section className="pgo-card"><style>{`.pgo-card{margin:0 0 18px;background:#fff;border:1px solid #e7e9ee;border-radius:14px;padding:18px 20px;box-shadow:0 2px 10px rgba(20,28,45,.03);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:#172033}.pgo-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:12px}.pgo-title{font-size:15px;font-weight:800}.pgo-sub{font-size:10px;color:#7d8594;margin-top:4px}.pgo-list{display:grid;gap:7px}.pgo-row{display:grid;grid-template-columns:1.2fr .8fr 1fr auto;gap:12px;align-items:center;padding:10px 11px;border:1px solid #eef0f3;border-radius:10px}.pgo-name{font-size:11px;font-weight:800}.pgo-meta{font-size:9px;color:#7d8594;margin-top:3px}.pgo-next{font-size:10px;font-weight:700}.pgo-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:#fff5df;color:#996400;font-size:9px;font-weight:800;white-space:nowrap}.pgo-link{font-size:9px;font-weight:800;color:#172b4d;text-decoration:none}.pgo-link:hover{text-decoration:underline}@media(max-width:800px){.pgo-row{grid-template-columns:1fr 1fr}.pgo-link{justify-self:start}}@media(max-width:520px){.pgo-row{grid-template-columns:1fr}}`}</style><div className="pgo-head"><div><div className="pgo-title">Percorso post-GO</div><div className="pgo-sub">Solo progetti con GO già registrato: qui si vede il prossimo passaggio societario, senza duplicare la scheda progetto.</div></div><span className="pgo-badge">{rows.length} GO attivi</span></div><div className="pgo-list">{rows.map((p) => <div className="pgo-row" key={p.project_id}><div><div className="pgo-name">{p.project_name}</div><div className="pgo-meta">{p.responsible_name || "Responsabile da assegnare"}</div></div><div className="pgo-meta">{spvLabel[p.spv_status] || "SPV: da avviare"}<br/>{transferLabel[p.connection_transfer_status] || "Voltura: da avviare"}</div><div className="pgo-next">{next(p)}</div><Link className="pgo-link" href={`/visconti-work/projects?id=${p.project_id}`}>Apri progetto →</Link></div>)}</div></section>;
}
