"use client";

import Link from "next/link";

function fmt(v){return v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString("it-IT"):"—";}
function daysTo(v){if(!v)return null;const today=new Date();today.setHours(0,0,0,0);const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return Math.round((d-today)/86400000);}
function tone(v){return v<0?"red":v<=7?"amber":"green";}
function Badge({children,tone="green"}){return <span className={`db-badge db-${tone}`}>{children}</span>}

export default function ViscontiDeadlineBoard({tasks=[],deadlines=[],projects=[],members=[]}){
 const projectMap=new Map(projects.map(p=>[p.id,p.name]));
 const memberMap=new Map(members.map(m=>[m.id,m.display_name]));
 const taskRows=tasks.filter(t=>t.due_date&&!['done','cancelled'].includes(t.workflow_status)).map(t=>({id:`task-${t.id}`,project_id:t.project_id,title:t.title,due_date:t.due_date,status:t.workflow_status,responsible_id:t.responsible_id,source:"Attività",link:`/visconti-work/tasks?task=${encodeURIComponent(t.id)}&project=${encodeURIComponent(t.project_id||"")}`}));
 const deadlineRows=deadlines.filter(d=>d.due_date).map(d=>({id:`deadline-${d.id}`,practice_id:d.practice_id,title:d.title,due_date:d.due_date,status:d.status,responsible_id:d.responsible_id,source:"Connessione",link:`/visconti-work/connection?practice=${encodeURIComponent(d.practice_id||"")}`}));
 const rows=[...taskRows,...deadlineRows].sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)));
 const overdue=rows.filter(r=>daysTo(r.due_date)<0).length;
 const soon=rows.filter(r=>{const d=daysTo(r.due_date);return d!==null&&d>=0&&d<=7}).length;
 return <main className="db-shell"><style>{`.db-shell{min-height:100vh;background:#f6f7f9;color:#172033;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.db-top{background:#fff;border-bottom:1px solid #e7e9ee;padding:14px 34px;display:flex;justify-content:space-between;align-items:center;gap:15px}.db-brand{font-weight:800}.db-nav{display:flex;gap:6px;flex-wrap:wrap}.db-nav a{padding:8px 11px;border-radius:9px;color:#687181;text-decoration:none;font-size:12px;font-weight:750}.db-nav a:hover,.db-nav .active{background:#172033;color:#fff}.db-main{max-width:1300px;margin:auto;padding:30px 34px 50px}.db-kicker{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#8a92a1;font-weight:800}.db-title{font-size:30px;letter-spacing:-.04em;margin:5px 0}.db-sub{font-size:13px;color:#737c8c}.db-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.db-kpi,.db-card{background:#fff;border:1px solid #e7e9ee;border-radius:14px}.db-kpi{padding:15px}.db-kpi small{display:block;color:#7d8594;font-size:10px;text-transform:uppercase}.db-kpi b{display:block;font-size:25px;margin-top:5px}.db-card{padding:19px}.db-table{width:100%;border-collapse:collapse}.db-table th{text-align:left;color:#9299a6;font-size:10px;text-transform:uppercase;padding:10px 8px}.db-table td{padding:13px 8px;border-top:1px solid #eef0f3;font-size:11px}.db-link{color:inherit;text-decoration:none}.db-link:hover{text-decoration:underline}.db-muted{color:#7d8594}.db-badge{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:800;white-space:nowrap}.db-red{background:#fff0ef;color:#b43a34}.db-amber{background:#fff5df;color:#996400}.db-green{background:#eaf8f1;color:#18794e}.db-empty{padding:28px 0;color:#7d8594;font-size:12px}.db-note{margin-top:12px;font-size:10px;color:#7d8594}@media(max-width:750px){.db-main{padding:22px 16px}.db-grid{grid-template-columns:1fr 1fr}.db-table th:nth-child(3),.db-table td:nth-child(3){display:none}}@media(max-width:500px){.db-grid{grid-template-columns:1fr}.db-table th:nth-child(4),.db-table td:nth-child(4){display:none}}`}</style>
 <header className="db-top"><div className="db-brand">GRUPPO VISCONTI · WORK V2</div><nav className="db-nav"><Link href="/visconti-work">Control Tower</Link><Link href="/visconti-work/projects">Progetti</Link><Link href="/visconti-work/tasks">Attività</Link><Link className="active" href="/visconti-work/deadlines">Scadenze</Link><Link href="/visconti-work/meetings">Riunioni</Link></nav></header>
 <section className="db-main"><div className="db-kicker">Controllo operativo</div><h1 className="db-title">Scadenze</h1><p className="db-sub">Un'unica vista delle scadenze già registrate. Nessuna data viene calcolata o inventata.</p>
 <div className="db-grid"><div className="db-kpi"><small>Totali registrate</small><b>{rows.length}</b></div><div className="db-kpi"><small>Scadute</small><b>{overdue}</b></div><div className="db-kpi"><small>Entro 7 giorni</small><b>{soon}</b></div></div>
 <section className="db-card">{rows.length?<table className="db-table"><thead><tr><th>Scadenza</th><th>Progetto</th><th>Responsabile</th><th>Fonte</th><th>Stato</th></tr></thead><tbody>{rows.map(r=>{const d=daysTo(r.due_date);return <tr key={r.id}><td><Link className="db-link" href={r.link}><b>{fmt(r.due_date)}</b><div className="db-muted">{r.title}</div></Link></td><td>{projectMap.get(r.project_id)||projectMap.get(deadlines.find(x=>`deadline-${x.id}`===r.id)?.project_id)||"—"}</td><td>{memberMap.get(r.responsible_id)||"Non assegnato"}</td><td>{r.source}</td><td><Badge tone={tone(d)}>{d<0?`${Math.abs(d)} gg di ritardo`:d===0?"Oggi":`tra ${d} gg`}</Badge></td></tr>})}</tbody></table>:<div className="db-empty">Nessuna scadenza registrata.</div>}<div className="db-note">Le scadenze delle connessioni vengono mostrate solo se presenti nel registro della pratica; le scadenze delle attività provengono dalla coda operativa.</div></section>
 </section></main>;
}
