"use client";

import Link from "next/link";

function fmt(v){return v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString("it-IT"):"—";}
function Badge({children,tone="blue"}){return <span className={`wm-badge wm-${tone}`}>{children}</span>}

export default function ViscontiWeeklyMeeting({data={}}){
 const projects=data.projects||[], tasks=data.tasks||[];
 const open=tasks.filter(t=>!["done","cancelled"].includes(t.workflow_status));
 const blocked=open.filter(t=>t.workflow_status==="blocked"||t.attention_state==="blocked");
 const overdue=open.filter(t=>t.attention_state==="overdue");
 const urgent=open.filter(t=>t.attention_state==="urgent");
 const waiting=projects.reduce((s,p)=>s+Number(p.waiting_terna_confirmations||0),0);
 const rejected=projects.reduce((s,p)=>s+Number(p.rejected_terna_confirmations||0),0);
 const spvProjects=projects.filter(p=>p.go_no_go_status==="go" && p.connection_transfer_status!=="completed");
 const spvAttention=spvProjects.filter(p=>p.spv_attention);
 const focus=[...blocked,...overdue,...urgent].filter((t,i,a)=>a.findIndex(x=>x.id===t.id)===i).slice(0,12);
 const decisions=projects.filter(p=>Number(p.blockers||0)>0||Number(p.rejected_terna_confirmations||0)>0||p.spv_attention).slice(0,10);
 return <main className="wm-shell"><style>{`.wm-shell{min-height:100vh;background:#f6f7f9;color:#172033;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.wm-top{background:#fff;border-bottom:1px solid #e7e9ee;padding:14px 34px;display:flex;justify-content:space-between;align-items:center}.wm-brand{font-weight:800}.wm-nav{display:flex;gap:6px;flex-wrap:wrap}.wm-nav a{padding:8px 11px;border-radius:9px;color:#687181;text-decoration:none;font-size:12px;font-weight:750}.wm-nav a:hover,.wm-nav .active{background:#172033;color:#fff}.wm-main{max-width:1320px;margin:auto;padding:30px 34px 50px}.wm-kicker{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#8a92a1;font-weight:800}.wm-title{font-size:30px;letter-spacing:-.04em;margin:5px 0}.wm-sub{font-size:13px;color:#737c8c}.wm-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:20px 0}.wm-kpi,.wm-card{background:#fff;border:1px solid #e7e9ee;border-radius:14px}.wm-kpi{padding:15px}.wm-kpi small{display:block;color:#7d8594;font-size:10px;text-transform:uppercase}.wm-kpi b{display:block;font-size:25px;margin-top:5px}.wm-columns{display:grid;grid-template-columns:1.25fr .75fr;gap:18px}.wm-card{padding:19px}.wm-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.wm-head strong{font-size:14px}.wm-row{display:grid;grid-template-columns:1.5fr .8fr .7fr auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid #eef0f3;text-decoration:none;color:inherit;font-size:11px}.wm-row:first-of-type{border-top:0}.wm-meta{color:#7d8594;font-size:10px;margin-top:3px}.wm-badge{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:800;white-space:nowrap}.wm-red{background:#fff0ef;color:#b43a34}.wm-amber{background:#fff5df;color:#996400}.wm-blue{background:#edf3ff;color:#3d61ad}.wm-green{background:#eaf8f1;color:#18794e}.wm-box{border:1px solid #eef0f3;border-radius:10px;padding:12px;margin-bottom:8px}.wm-box b{font-size:11px}.wm-box p{font-size:10px;color:#747d8b;line-height:1.45;margin:5px 0 0}.wm-box a{display:inline-block;margin-top:8px;font-size:10px;font-weight:800;color:#3d61ad;text-decoration:none}.wm-empty{font-size:11px;color:#7d8594;padding:10px 0}.wm-actions{display:flex;gap:8px;margin-top:16px}.wm-btn{padding:9px 12px;border:1px solid #dfe3e9;border-radius:9px;text-decoration:none;color:#172033;font-size:11px;font-weight:750}.wm-primary{background:#172b4d;color:#fff;border-color:#172b4d}@media(max-width:850px){.wm-grid{grid-template-columns:1fr 1fr}.wm-columns{grid-template-columns:1fr}.wm-main{padding:22px 18px}}@media(max-width:600px){.wm-row{grid-template-columns:1fr 1fr}.wm-row div:nth-child(4){grid-column:span 2}}`}</style>
 <header className="wm-top"><div className="wm-brand">GRUPPO VISCONTI · WORK V2</div><nav className="wm-nav"><Link href="/visconti-work">Control Tower</Link><Link href="/visconti-work/projects">Progetti</Link><Link href="/visconti-work/tasks">Attività</Link><Link className="active" href="/visconti-work/meetings">Riunioni</Link></nav></header>
 <section className="wm-main"><div className="wm-kicker">Riunione settimanale · preparazione operativa</div><h1 className="wm-title">Riunione settimanale</h1><p className="wm-sub">Agenda generata automaticamente dai dati già presenti: si discutono solo blocchi, scadenze, attività critiche, decisioni e passaggi GO → SPV → voltura.</p>
 <div className="wm-grid"><div className="wm-kpi"><small>Progetti</small><b>{projects.length}</b></div><div className="wm-kpi"><small>Attività aperte</small><b>{open.length}</b></div><div className="wm-kpi"><small>Blocchi / scadute</small><b>{blocked.length+overdue.length}</b></div><div className="wm-kpi"><small>Conferme esterne</small><b>{waiting}</b><div style={{fontSize:10,color:'#7d8594',marginTop:3}}>{rejected} da verificare</div></div><div className="wm-kpi"><small>SPV / volture</small><b>{spvAttention.length}</b><div style={{fontSize:10,color:'#7d8594',marginTop:3}}>{spvProjects.length} GO aperti</div></div></div>
 <div className="wm-columns"><section className="wm-card"><div className="wm-head"><strong>Ordine del giorno</strong><Badge tone={focus.length||spvAttention.length?"amber":"green"}>{focus.length||spvAttention.length?`${focus.length+spvAttention.length} punti da trattare`:"Nessun punto critico"}</Badge></div>
 {spvAttention.map(p=><Link className="wm-row" key={`spv-${p.project_id}`} href={`/visconti-work/projects?id=${encodeURIComponent(p.project_id)}`}><div><b>{p.project_name}</b><div className="wm-meta">GO confermato · {p.spv_attention}</div></div><div>{p.responsible_name||"Non assegnato"}</div><div>{fmt(p.go_no_go_date)}</div><Badge tone="amber">SPV / voltura</Badge></Link>)}
 {focus.map(t=><Link className="wm-row" key={t.id} href={`/visconti-work/tasks?task=${encodeURIComponent(t.id)}&project=${encodeURIComponent(t.project_id||"")}`}><div><b>{t.title}</b><div className="wm-meta">{t.project_name||"Progetto non indicato"} · {t.next_action||"Definire prossima azione"}</div></div><div>{t.assignee_name||"Non assegnata"}</div><div>{fmt(t.due_date)}</div><Badge tone={t.workflow_status==="blocked"?"red":"amber"}>{t.workflow_status==="blocked"?"Bloccata":t.attention_state==="overdue"?"Scaduta":"Urgente"}</Badge></Link>)}
 {!focus.length&&!spvAttention.length&&<div className="wm-empty">Nessun elemento critico rilevato.</div>}</section>
 <aside><section className="wm-card"><div className="wm-head"><strong>Decisioni da preparare</strong><span style={{fontSize:10,color:'#7d8594'}}>{decisions.length}</span></div>{decisions.length?decisions.map(p=><div className="wm-box" key={p.project_id}><b>{p.project_name}</b><p>{p.spv_attention?`${p.spv_attention}: definire chi fa il prossimo passaggio e entro quando.`:Number(p.rejected_terna_confirmations||0)>0?"Verificare il riscontro esterno e decidere il seguito.":`${p.blockers||0} blocchi aperti: definire responsabile e azione di sblocco.`}</p><Link href={`/visconti-work/projects?id=${encodeURIComponent(p.project_id)}`}>Apri progetto →</Link></div>):<div className="wm-empty">Nessuna decisione critica preclassificata.</div>}</section>
 <section className="wm-card" style={{marginTop:18}}><div className="wm-head"><strong>Chiusura riunione</strong></div><div className="wm-box"><b>Ogni decisione deve produrre un'azione</b><p>Definire responsabile, azione e scadenza. L'azione resta nella sezione Attività e si riflette nel Progetto.</p></div><div className="wm-actions"><Link className="wm-btn wm-primary" href="/visconti-work/projects">Apri progetti</Link><Link className="wm-btn" href="/visconti-work/tasks">Apri attività</Link></div></section></aside></div></section></main>;
}
