"use client";

import { useMemo, useState } from "react";

const statusLabel = { pending:"Da avviare", active:"Attiva", accepted:"Accettata" };
function Badge({ children, tone="neutral" }) { return <span className={`cl-badge cl-${tone}`}>{children}</span>; }

export default function ViscontiConnectionListV2({ connections = [], connected = false }) {
  const [query, setQuery] = useState("");
  const rows = useMemo(() => connections.filter(c => `${c.project_name||""} ${c.practice_code||""} ${c.operator||""}`.toLowerCase().includes(query.toLowerCase())), [connections, query]);
  return <main className="cl-shell"><style>{`.cl-shell{min-height:100vh;background:#f6f7f9;color:#172033;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.cl-top{background:#fff;border-bottom:1px solid #e6e9ef;padding:15px 34px;display:flex;justify-content:space-between;align-items:center}.cl-brand{font-weight:800;font-size:14px}.cl-back{display:block;color:#697386;text-decoration:none;font-size:11px;margin-bottom:4px}.cl-main{max-width:1320px;margin:auto;padding:30px 34px 50px}.cl-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.cl-kicker{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#8a92a1;font-weight:800}.cl-title{font-size:30px;letter-spacing:-.04em;margin:5px 0}.cl-sub{font-size:13px;color:#737c8c}.cl-actions{display:flex;gap:8px}.cl-btn{border:1px solid #dfe3e9;background:#fff;border-radius:9px;padding:9px 13px;font-size:11px;font-weight:750;text-decoration:none;color:#172033}.cl-primary{background:#172b4d;color:#fff;border-color:#172b4d}.cl-tools{margin:22px 0 12px}.cl-input{width:min(420px,100%);box-sizing:border-box;border:1px solid #dfe3e9;border-radius:9px;background:#fff;padding:9px 11px;font:inherit;font-size:11px}.cl-card{background:#fff;border:1px solid #e6e9ef;border-radius:14px;overflow:hidden;box-shadow:0 2px 10px rgba(20,28,45,.03)}.cl-row{display:grid;grid-template-columns:1.5fr .9fr .7fr 1fr .8fr .8fr;gap:12px;padding:14px 16px;border-top:1px solid #edf0f3;align-items:center}.cl-row:first-child{border-top:0}.cl-headrow{background:#fafbfc;color:#9299a6;text-transform:uppercase;letter-spacing:.06em;font-size:9px;font-weight:800}.cl-row:not(.cl-headrow){font-size:11px}.cl-name{font-weight:800;font-size:12px}.cl-muted{color:#7c8493;font-size:10px;margin-top:3px}.cl-badge{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:800;white-space:nowrap}.cl-normal{background:#edf3ff;color:#3d61ad}.cl-soon{background:#fff5df;color:#996400}.cl-overdue{background:#fff0ef;color:#b43a34}.cl-neutral{background:#f0f2f5;color:#626b7a}.cl-empty{padding:35px;text-align:center;color:#7c8493;font-size:12px}.cl-note{margin-top:12px;color:#8a92a1;font-size:10px}@media(max-width:900px){.cl-main{padding:22px 18px}.cl-top{padding:14px 18px}.cl-row{grid-template-columns:1.5fr 1fr .7fr}.cl-headrow{display:none}.cl-row>div:nth-child(n+4){display:none}}`}</style>
    <header className="cl-top"><div><a className="cl-back" href="/visconti-work">← Control Tower</a><div className="cl-brand">GRUPPO VISCONTI · WORK V2</div></div><div className="cl-actions"><a className="cl-btn" href="/visconti-work/projects">Progetti</a></div></header>
    <section className="cl-main"><div className="cl-head"><div><div className="cl-kicker">Connessioni</div><h1 className="cl-title">Pratiche di connessione</h1><p className="cl-sub">PTO, iter autorizzativo e scadenze Terna in una sola vista.</p></div><a className="cl-btn cl-primary" href="/visconti-work">Control Tower</a></div>
      <div className="cl-tools"><input className="cl-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca progetto, pratica o operatore…"/></div>
      <div className="cl-card"><div className="cl-row cl-headrow"><div>Progetto</div><div>Operatore</div><div>MW</div><div>Pratica</div><div>Stato</div><div>Prossima scadenza</div></div>{rows.map(c=><a key={c.id} href={`/visconti-work/connection?practice=${encodeURIComponent(c.id)}`} className="cl-row" style={{textDecoration:"none",color:"inherit"}}><div><div className="cl-name">{c.project_name}</div><div className="cl-muted">{c.region||"Regione non indicata"}</div></div><div>{c.operator||"—"}</div><div>{c.power_mw||0}</div><div><b>{c.practice_code||"Senza codice"}</b><div className="cl-muted">{c.station||"Stazione non indicata"}</div></div><div><Badge tone={c.attention_state}>{statusLabel[c.status]||c.status||"—"}</Badge></div><div>{c.next_deadline||"Nessuna"}</div></a>)}{!rows.length&&<div className="cl-empty">{connected?"Nessuna pratica corrisponde alla ricerca.":"Nessun dato Supabase disponibile. Configura il collegamento per vedere le pratiche reali."}</div>}</div>
      <div className="cl-note">{connected ? `${rows.length} pratiche visualizzate.` : "Modalità dimostrativa: la struttura è pronta, ma le pratiche reali richiedono Supabase configurato."}</div>
    </section></main>;
}
