"use client";

import Link from "next/link";

const statusLabel={todo:"Da fare",in_progress:"In attesa / in corso",blocked:"Bloccata",done:"Completata",cancelled:"Annullata"};
function fmt(d){if(!d)return"—";return new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${d}T00:00:00`))}
function tone(t){if(t.attention_state==='overdue'||t.priority==='urgent')return'vt-red';if(t.workflow_status==='blocked'||t.priority==='high')return'vt-amber';if(t.workflow_status==='done')return'vt-green';return'vt-blue'}

export default function ViscontiTaskBoardTernaV2({tasks=[],connected=false}){
 const terna=tasks.filter(t=>t.is_connection_deadline_task||t.source_connection_step_id);
 const confirmations=terna.filter(t=>Boolean(t.source_connection_step_id));
 const open=terna.filter(t=>!['done','cancelled'].includes(t.workflow_status));
 const waiting=confirmations.filter(t=>t.workflow_status!=='done'&&t.workflow_status!=='cancelled');
 return <main className="vtt-shell"><style>{`.vtt-shell{min-height:100vh;background:#f6f7f9;color:#172033;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.vtt-top{background:#fff;border-bottom:1px solid #e7e9ee;padding:14px 34px;display:flex;justify-content:space-between;align-items:center}.vtt-brand{font-weight:800}.vtt-nav{display:flex;gap:6px}.vtt-nav a{padding:8px 11px;border-radius:9px;color:#687181;text-decoration:none;font-size:12px;font-weight:750}.vtt-nav a:hover,.vtt-nav .active{background:#172033;color:#fff}.vtt-main{max-width:1440px;margin:auto;padding:30px 34px}.vtt-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.vtt-kicker{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#8a92a2;font-weight:750}.vtt-title{font-size:30px;letter-spacing:-.04em;margin:5px 0}.vtt-desc{font-size:14px;color:#70798a}.vtt-link{color:#315aa8;text-decoration:none}.vtt-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.vtt-card{background:#fff;border:1px solid #e7e9ee;border-radius:14px;box-shadow:0 2px 10px rgba(20,28,45,.03)}.vtt-kpi{padding:16px 18px}.vtt-kpi span{font-size:11px;color:#7d8594}.vtt-kpi strong{display:block;font-size:25px;margin-top:5px}.vtt-note{padding:14px 16px;margin-bottom:16px;font-size:12px;color:#5d6675}.vtt-table{width:100%;border-collapse:collapse}.vtt-table th{padding:11px 12px;text-align:left;color:#98a0ad;font-size:10px;text-transform:uppercase;letter-spacing:.08em}.vtt-table td{padding:14px 12px;border-top:1px solid #eef0f3;font-size:12px;vertical-align:middle}.vtt-badge{display:inline-flex;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:800}.vt-blue{background:#edf3ff;color:#3d61ad}.vt-green{background:#eaf8f1;color:#18794e}.vt-amber{background:#fff5df;color:#996400}.vt-red{background:#fff0ef;color:#b43a34}.vtt-muted{color:#7d8594}.vtt-actions{display:flex;gap:6px;flex-wrap:wrap}.vtt-action{border:1px solid #dfe3e9;background:#fff;border-radius:8px;padding:7px 9px;text-decoration:none;color:#172033;font-size:10px;font-weight:750}.vtt-empty{padding:36px;text-align:center;color:#7d8594}@media(max-width:800px){.vtt-kpis{grid-template-columns:1fr 1fr}.vtt-main{padding:22px 16px;overflow:auto}.vtt-top{padding:14px 18px;gap:12px;flex-wrap:wrap}}`}</style>
 <header className="vtt-top"><div className="vtt-brand">GRUPPO VISCONTI <span className="vtt-muted"> · CONTROLLO TERNA</span></div><nav className="vtt-nav"><Link href="/visconti-work">Control Tower</Link><Link href="/visconti-work/projects">Progetti</Link><Link href="/visconti-work/tasks" className="active">Attività</Link><Link href="/visconti-work/connection">Connessioni</Link></nav></header>
 <section className="vtt-main"><div className="vtt-head"><div><div className="vtt-kicker">Terna · task engine</div><h1 className="vtt-title">Controllo connessioni</h1><p className="vtt-desc">Qui confluiscono scadenze e attese di conferma Terna. Ogni elemento resta collegato alla pratica originale.</p></div><Link className="vtt-action" href="/visconti-work/connection">Gestisci connessioni</Link></div>
 <div className="vtt-kpis"><div className="vtt-card vtt-kpi"><span>Elementi Terna</span><strong>{terna.length}</strong></div><div className="vtt-card vtt-kpi"><span>Da chiudere</span><strong>{open.length}</strong></div><div className="vtt-card vtt-kpi"><span>In attesa conferma</span><strong>{waiting.length}</strong></div><div className="vtt-card vtt-kpi"><span>Bloccate / da verificare</span><strong>{terna.filter(t=>t.workflow_status==='blocked').length}</strong></div></div>
 <div className="vtt-card vtt-note"><strong>Regola operativa:</strong> una fase con conferma Terna crea automaticamente una attività di attesa. Quando registri <b>Confermato</b> o <b>Validato</b>, l'attività viene chiusa; un rigetto rimane evidenziato come blocco.</div>
 <section className="vtt-card">{terna.length?<table className="vtt-table"><thead><tr><th>Elemento</th><th>Pratica</th><th>Progetto</th><th>Responsabile</th><th>Scadenza</th><th>Stato</th><th></th></tr></thead><tbody>{terna.map(t=><tr key={t.id}><td><strong>{t.connection_deadline_title||t.title.replace('Connessione — ','')}</strong><div className="vtt-muted">{t.source_connection_step_id?'Conferma / validazione Terna':t.connection_deadline_type||'deadline'}</div></td><td>{t.connection_practice_code||'—'}</td><td>{t.project_id?<Link className="vtt-link" href={`/visconti-work/projects?id=${t.project_id}`}>{t.project_name||'Progetto'}</Link>:'—'}</td><td>{t.assignee_name||'Non assegnata'}</td><td><span className={`vtt-badge ${tone(t)}`}>{fmt(t.due_date)}</span></td><td><span className={`vtt-badge ${tone(t)}`}>{statusLabel[t.workflow_status]||t.workflow_status}</span></td><td><div className="vtt-actions">{t.connection_practice_id&&<Link className="vtt-action" href={`/visconti-work/connection?practice=${t.connection_practice_id}`}>Apri pratica</Link>}</div></td></tr>)}</tbody></table>:<div className="vtt-empty">Nessuna scadenza o attesa Terna è ancora collegata a una attività.</div>}</section>
 {!connected&&<div className="vtt-note" style={{marginTop:12}}>Database non configurato: vista informativa.</div>}
 </section></main>
}
